config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :recipes do
  resources :recipe_foods
  end
  resources :shopping_lists, only: [:index]
  resources :foods
  resources :public_recipes, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "public_recipes#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    # can :destroy, Recipe, user:
    cannot :read, Recipe, public: false
    return unless user.present?

    can(:manage, Recipe, user:)
    can(:manage, Food, user:)
    can(:manage, RecipeFood, user:)
    return unless user.role == 'admin'

    can :manage, all
  end
end

app/models/add_devise_to_user.rb
class AddDeviseToUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  # GET /foods or /foods.json
  def index
    @foods = Food.all.where(user_id: current_user.id).order(created_at: :desc)
  end

  # GET /foods/1 or /foods/1.json
  def show
    @food = Food.find_by(id: params[:id])
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods or /foods.json
  def create
    # @food = Food.new(food_params)
    # @food = current_user.foods.new(food_params)
    measurement_unit = params[:food][:measurement_unit]
    prices = params[:food][:price]
    quantity = params[:food][:quantity]

    @food = Food.new(user: current_user, name: params[:food][:name], measurement_unit:, price: prices, quantity:)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food = Food.find_by(id: params[:id])

    respond_to do |format|
      if @food.destroy
        format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      else
        format.html { redirect_to foods_url, error: 'Failed to Delete the Food.' }
      end
    end
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.all.includes(:user).where(public: 'true').order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = RecipeFood.all
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  # def show
  # end

  # GET /recipe_foods/new
  def new
    @recipe_food = RecipeFood.new
    @all_foods = current_user.foods.all
  end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @new_recipe_food = @recipe.recipe_foods.new(recipe_food_params)

    respond_to do |format|
      if @new_recipe_food.save
        format.html { redirect_to recipe_path(@recipe), notice: 'Recipe food was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find_by(id: params[:id])
    respond_to do |format|
      if @recipe_food.destroy
        format.html { redirect_to recipe_path(@recipe), notice: 'Recipe food was successfully destroyed.' }
      else
        format.html { redirect_to recipe_recipe_food_url, notice: 'Failed to delete Recipe Food. Please try again!' }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user).order(created_at: :desc)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find_by(id: params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  # def edit
  # end

  # POST /recipes or /recipes.json
  def create
    @new_recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @new_recipe.save
        format.html { redirect_to recipes_url(@new_recipe), notice: 'Recipe was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = Recipe.find_by(id: params[:id])

    respond_to do |format|
      if @recipe.destroy
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      else
        format.html { redirect_to recipe_url, notice: 'Failed to delete the recipe. Please try again!' }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  # def show
  # end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/header" %>
  <div class="container", style="min-height: 84vh;">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
<%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3t text-light">
    © 2023 Copyright <br>
    <a class="text-blue text-decoration-none" href="https://github.com/Harrynoqs">Harrison Njuguna</a> &
    <a class="text-blue text-decoration-none" href="https://github.com/degisew">Degisew Mengist</a> 
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Recipe App', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to 'Foods', foods_url, class: 'nav-link'%>
        </li>
        <li class='nav-item'>
         <%= link_to 'Recipes', recipes_url, class: 'nav-link'  %>
        </li>
         <li class='nav-item'>
           <%= link_to ' Public Recipes', public_recipes_url, class: 'nav-link' %>
         </li>
          <li class='nav-item'>
            <%= link_to 'Shopping List', shopping_lists_url, class: 'nav-link' %>
          </li>
      </ul>

    </div>
    <li class="d-flex justify-content-end ml-auto">
        <% if user_signed_in? %>
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-light  text-end', data: { turbo: false } %>
        <% else %>
        <%= button_to 'Sign In', new_user_session_path, class: 'nav-link btn btn-light text-end'%>
        <% end%>
        </li>
  </div>
</nav>