config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :recipes do
  resources :recipe_foods
  end
  resources :shopping_lists, only: [:index]
  resources :foods
  resources :public_recipes, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "public_recipes#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    # can :destroy, Recipe, user:
    cannot :read, Recipe, public: false
    return unless user.present?

    can(:manage, Recipe, user:)
    can(:manage, Food, user:)
    can(:manage, RecipeFood, user:)
    return unless user.role == 'admin'

    can :manage, all
  end
end

app/models/add_devise_to_user.rb
class AddDeviseToUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  # GET /foods or /foods.json
  def index
    @foods = Food.all.where(user_id: current_user.id).order(created_at: :desc)
  end

  # GET /foods/1 or /foods/1.json
  def show
    @food = Food.find_by(id: params[:id])
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods or /foods.json
  def create
    # @food = Food.new(food_params)
    # @food = current_user.foods.new(food_params)
    measurement_unit = params[:food][:measurement_unit]
    prices = params[:food][:price]
    quantity = params[:food][:quantity]

    @food = Food.new(user: current_user, name: params[:food][:name], measurement_unit:, price: prices, quantity:)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food = Food.find_by(id: params[:id])

    respond_to do |format|
      if @food.destroy
        format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      else
        format.html { redirect_to foods_url, error: 'Failed to Delete the Food.' }
      end
    end
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.all.includes(:user).where(public: 'true').order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = RecipeFood.all
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  # def show
  # end

  # GET /recipe_foods/new
  def new
    @recipe_food = RecipeFood.new
    @all_foods = current_user.foods.all
  end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @new_recipe_food = @recipe.recipe_foods.new(recipe_food_params)

    respond_to do |format|
      if @new_recipe_food.save
        format.html { redirect_to recipe_path(@recipe), notice: 'Recipe food was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find_by(id: params[:id])
    respond_to do |format|
      if @recipe_food.destroy
        format.html { redirect_to recipe_path(@recipe), notice: 'Recipe food was successfully destroyed.' }
      else
        format.html { redirect_to recipe_recipe_food_url, notice: 'Failed to delete Recipe Food. Please try again!' }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user).order(created_at: :desc)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find_by(id: params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  # def edit
  # end

  # POST /recipes or /recipes.json
  def create
    @new_recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @new_recipe.save
        format.html { redirect_to recipes_url(@new_recipe), notice: 'Recipe was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = Recipe.find_by(id: params[:id])

    respond_to do |format|
      if @recipe.destroy
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      else
        format.html { redirect_to recipe_url, notice: 'Failed to delete the recipe. Please try again!' }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :authenticate_user!
  def index
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @shopping_lists = RecipeFood.includes(:food).all
    @total_price = sum(@shopping_lists)
  end

  private

  def sum(shopping_lists)
    total = 0
    shopping_lists.each do |item|
      total += item.food.price * item.quantity.to_i
    end
    total
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  # def show
  # end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">

  <tr>
    <td><%= food.name%></td>
    <td><%= food.measurement_unit%></td>
    <td><%= food.price%></td>
    <td><%= button_to 'Delete', food, method: :delete, data: { turbo_confirm: "Are you sure?"}, class: "delete-food-btn"%></td>
  </tr>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit 'Add Food'%>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="foods">
<%= link_to "Add New food", new_food_path, class: 'add-food-link'%>
  <table>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Measurement unit</th>
      <th scope="col">Unit price</th>
      <th scope="col">Action</th>
    </tr>
    <% @foods.each do |food| %>
      <%= render food %>
    <% end %>
  </table>
</div>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/public_recipes/_index.html.erb
<div id="<%= dom_id recipe %>">
  <div class="recipe-card">
    <div class="recipe-name-contnr">
        <h5>
          <%= recipe.name %>
        </h5>
        <h4>By: <%= recipe.user.name %></h4>
    </div>
      <div class="recipe-descrptn-contnr">
        <p>
          <%= recipe.description %>
        </p>
      </div>
  </div><br>
</div>

app/views/public_recipes/index.html.erb
<div>
  <% @public_recipes.each do |public_recipe| %>
  <%=render 'index', recipe: public_recipe %>
  <% end %>
</div>

app/views/recipe_foods/_form.html.erb
<%= form_with model: @recipe_food, url: recipe_recipe_foods_path do |form| %>
  <% if @recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% @recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :food, style: "display: block" %>
    <%= form.collection_select :food_id, @all_foods, :id, :name %>
  </div>

  <div class="create-recipe_food-btn">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/new.html.erb
<div class="add-recipe_food-form-container">
<div class="add-recipe_food-form">
<h1>New recipe food</h1>

<%= render "form", recipe_food: @recipe_food  %>

<br>
</div>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="recipe-form-fields">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="recipe-form-fields">
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div class="recipe-form-fields">
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div class="recipe-form-fields">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, style: "min-height: 100px; min-width: 400px" %>
  </div>

  <div class="recipe-form-fields">
    <%= form.label :public, style: "display: block" %>
    <%= form.select :public , [["Yes", true], ["No", false] ], selected: true  %>
  </div>

  <div class='create-recipe-btn'>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <div class="recipe-card">
  <div class="recipe-name-contnr">
  <%= link_to recipe_url(recipe), class: 'recipe-link' do %>
    <h5>
    <%= recipe.name %>
    </h5>
<% end %>
    <%= button_to 'Remove', recipe, method: :delete, data: { turbo_confirm: "Are you sure?"} %>
  </div>
  <%= link_to recipe_url(recipe), class: 'recipe-link' do %>
    <div class="recipe-descrptn-contnr">
      <p>
        <%= recipe.description %>
      </p>
    </div>
<% end %>
  </div><br>
</div>

app/views/recipes/_show.html.erb
<div>
<div class="recipe-detail">
  <h1 class="recipe-name"><%= recipe.name %></h1>
  <div class="recipe-info">
    <div class="toogle-switch-container">
      <strong>Preparation Time:
      <%= recipe.preparation_time %></strong>
      <div style="display:flex; align-items: center; font-weight: bolder">
      Public&nbsp; <label class="switch">
        <input type="checkbox" checked>
        <span class="slider round"></span>
      </label>
      </div>
    </div>
    <strong>Cooking Time:
      <%= recipe.cooking_time %></strong>
  </div>
  <div class="recipe-btns">
    <%= button_to 'Generate Shopping List', shopping_lists_url%>
    <%= button_to 'Add Ingredient' %>
  </div><hr>

  <%= link_to 'Add Food', new_recipe_recipe_food_url(recipe), class: 'add-food-link' %>
  <table style="margin-top: 5px">
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
    <% recipe.recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name%></td>
        <td><%= recipe_food.quantity%></td>
        <td><%= recipe_food.food.price%></td>
        <td><%= button_to 'Delete', recipe_recipe_food_path(@recipe.id, recipe_food.id), method: :delete,
                          data: { turbo_confirm: "Are you sure?"}, class: "delete-food-btn"%></td>
      </tr>
    <% end %>
  </table>
</div>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>


<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
<%= link_to "Add New recipe", new_recipe_path, class: 'add-recipe-link' %>
</div>

app/views/recipes/new.html.erb
<div class="add-recipe-form">

<h1>New Recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back", recipes_path, class: 'recipe-back-btn' %>
</div>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: 'show', locals: {recipe: @recipe} %>

app/views/shopping_lists/index.html.erb
<div class='shopping-list-contnr'>
<div>
  <div class='d-flex justify-content-evenly'>
    <h4>Amount of food items to buy: <%= @shopping_lists.count %></h4>
    <h4>Total price: <%= "$#{@total_price}" %></h4>
  </div>
  <table>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
    </tr>
    <% @shopping_lists.each do |shopping_list| %>
      <tr>
    <td><%= shopping_list.food.name%></td>
    <td><%= shopping_list.quantity%></td>
    <td><%= shopping_list.food.price%></td>
      </tr>
    <% end %>
  </table>

</div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<div id="users">
    <h2><%= 'Foods' %></h2>
</div>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>